name: Build
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build CXB on ubuntu-latest
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: yarn
    
    - name: Build
      run: yarn build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cxb-dist
        path: dist/client/
        retention-days: 1